"""Mock org data so the GUI is fully clickable without a real Salesforce org.

Demo mode powers the scripted UI test / screen recording: every selection list
is populated and every 'Generate' action renders a real document from a
synthetic `ObjectSpec`, exercising the actual render/export pipeline.
"""

from __future__ import annotations

from ..auth import OrgCredentials, OrgInfo
from ..metadata.catalog import ObjectRef, ProfileRef
from ..models import (
    ApexTriggerSpec,
    EmailAlertSpec,
    FieldPermission,
    FieldSpec,
    FlowSpec,
    LightningPageAssignment,
    ObjectGeneralInfo,
    ObjectPermission,
    ObjectSpec,
    ProfileSpec,
    RecordTypeSpec,
    ValidationRuleSpec,
    WorkflowRuleSpec,
)

DEMO_ORGS: list[OrgInfo] = [
    OrgInfo(alias="demo-prod", username="admin@demo.prod.com", is_default=True),
    OrgInfo(alias="demo-sandbox", username="admin@demo.sandbox.com"),
]

DEMO_OBJECTS: list[ObjectRef] = [
    ObjectRef("Account", "Account", False),
    ObjectRef("Contact", "Contact", False),
    ObjectRef("Opportunity", "Opportunity", False),
    ObjectRef("Case", "Case", False),
    ObjectRef("Claim__c", "Claim", True),
    ObjectRef("Invoice__c", "Invoice", True),
    ObjectRef("Training_Record__c", "Training Record", True),
    ObjectRef("CompSuite__Action_Item__c", "Action Item", True),
    ObjectRef("CompSuite__Audit__c", "Audit", True),
    ObjectRef("CompSuite__Document__c", "Document", True),
]

DEMO_PROFILES: list[ProfileRef] = [
    ProfileRef("Admin", "System Administrator", "Profile"),
    ProfileRef("Standard", "Standard User", "Profile"),
    ProfileRef("ReadOnly", "Read Only", "Profile"),
    ProfileRef("Sales_User_PS", "Sales User", "PermissionSet"),
    ProfileRef("Quality_Manager_PS", "Quality Manager", "PermissionSet"),
]


def demo_creds(org: OrgInfo) -> OrgCredentials:
    return OrgCredentials(
        alias=org.alias or org.username,
        access_token="DEMO-TOKEN",
        instance_url="https://demo.my.salesforce.com",
        username=org.username,
        org_id="00Dxx0000000DEMO",
        api_version="59.0",
    )


def _demo_profiles_for(obj: str) -> list[ProfileSpec]:
    specs: list[ProfileSpec] = []
    presets = [
        ("Admin", "System Administrator", "Profile", True, True),
        ("Standard", "Standard User", "Profile", True, False),
        ("ReadOnly", "Read Only", "Profile", False, False),
    ]
    for full, label, kind, can_edit, can_admin in presets:
        specs.append(
            ProfileSpec(
                full_name=full,
                label=label,
                kind=kind,
                object_permissions=[
                    ObjectPermission(
                        obj=obj,
                        create=can_edit,
                        read=True,
                        edit=can_edit,
                        delete=can_admin,
                        view_all=can_admin,
                        modify_all=can_admin,
                    )
                ],
                field_permissions=[
                    FieldPermission(field=f"{obj}.Status__c", readable=True, editable=can_edit),
                    FieldPermission(field=f"{obj}.Amount__c", readable=True, editable=can_edit),
                ],
            )
        )
    return specs


def make_demo_spec(api_name: str, label: str) -> ObjectSpec:
    """A small but realistic ObjectSpec so rendered demo output has real content."""
    return ObjectSpec(
        general=ObjectGeneralInfo(
            api_name=api_name,
            label=label,
            plural_label=f"{label}s",
            description=f"Demo {label} object generated by the test UI.",
            sharing_model="ReadWrite",
            history_tracking_enabled=True,
        ),
        fields=[
            FieldSpec(api_name="Name", label="Name", type="string", required=True),
            FieldSpec(
                api_name="Status__c",
                label="Status",
                type="picklist",
                picklist_values=["New", "In Progress", "Closed"],
                help_text="Lifecycle status of the record.",
            ),
            FieldSpec(api_name="Amount__c", label="Amount", type="currency"),
            FieldSpec(
                api_name="Margin__c",
                label="Margin",
                type="formula",
                formula="Amount__c * 0.2",
            ),
        ],
        profiles=_demo_profiles_for(api_name),
        record_types=[
            RecordTypeSpec(api_name="Standard", label="Standard", active=True),
            RecordTypeSpec(api_name="Expedited", label="Expedited", active=True),
        ],
        validation_rules=[
            ValidationRuleSpec(
                api_name="Amount_Required",
                active=True,
                description="Amount must be positive.",
                error_condition="Amount__c <= 0",
                error_message="Amount must be greater than zero.",
            )
        ],
        workflows=[
            WorkflowRuleSpec(
                api_name="Notify_On_Close",
                active=True,
                description="Notify owner when closed.",
                trigger_type="onCreateOrTriggeringUpdate",
            )
        ],
        flows=[
            FlowSpec(
                api_name="Auto_Assign",
                label="Auto Assign",
                process_type="AutoLaunchedFlow",
                status="Active",
            )
        ],
        email_alerts=[
            EmailAlertSpec(
                api_name="Closed_Alert",
                description="Send on close",
                template="Closed_Template",
                sender_type="CurrentUser",
                recipients=["role:Sales Manager"],
            )
        ],
        apex_triggers=[
            ApexTriggerSpec(
                name=f"{api_name.replace('__c', '')}Trigger",
                status="Active",
                api_version=59.0,
                events=["before insert", "after update"],
            )
        ],
        lightning_pages=[
            LightningPageAssignment(
                app="Sales", form_factor="Large", flexipage=f"{label}_Record_Page"
            )
        ],
    )
